services:
  # Bot Discord
  - type: web
    name: discord-bot-pdp
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: discord-images-db
          property: connectionString
      - key: PORT
        value: 10000
    
databases:
  # Base de donn√©es PostgreSQL
  - name: discord-images-db
    plan: free
    region: frankfurt
